# Streamlit secrets

[supabase]
url = "https://fdylwtlxsvqxxygmpnjw.supabase.co"
anon_key = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImZkeWx3dGx4c3ZxeHh5Z21wbmp3Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NjQ0NzkxMzEsImV4cCI6MjA4MDA1NTEzMX0.oAP9zZpNB8Q7zepCaOcP2EkDj-wcBeufgAw9eI81fQY"
